all:
	xxd -i xbackend.data > xbackend_data.h
	xxd -i cacert.pem > cacert_pem.h
	#xxd -i ../java/assets/404 > assets_404.h
	#xxd -i ../java/assets/favicon.ico > assets_favicon_ico.h
	#xxd -i ../java/assets/INDEX.html > assets_INDEX_html.h
    
