source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '14.0'

target 'Envoy_Example' do
  pod 'Envoy', :path => '../'
  pod 'IEnvoyProxy', :path => '../../../IEnvoyProxy'
end
